//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CognitiveSoftware.TeamFoundation.Integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CognitiveSoftware.TeamFoundation.Integration.Resources.TR", typeof(TR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Sil.
        /// </summary>
        internal static string admindeletebtn {
            get {
                return ResourceManager.GetString("admindeletebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup İşlemleri.
        /// </summary>
        internal static string admingroupopbtn {
            get {
                return ResourceManager.GetString("admingroupopbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Listesi.
        /// </summary>
        internal static string adminuserlistbtn {
            get {
                return ResourceManager.GetString("adminuserlistbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string areapath {
            get {
                return ResourceManager.GetString("areapath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string bug {
            get {
                return ResourceManager.GetString("bug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklik İsteği.
        /// </summary>
        internal static string changereq {
            get {
                return ResourceManager.GetString("changereq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Yarat.
        /// </summary>
        internal static string createworkitem {
            get {
                return ResourceManager.GetString("createworkitem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama:.
        /// </summary>
        internal static string description2 {
            get {
                return ResourceManager.GetString("description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay Bilgisi.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntüle.
        /// </summary>
        internal static string LabelDetail {
            get {
                return ResourceManager.GetString("LabelDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje:.
        /// </summary>
        internal static string project2 {
            get {
                return ResourceManager.GetString("project2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Durumu.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öncelik:.
        /// </summary>
        internal static string severity2 {
            get {
                return ResourceManager.GetString("severity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Aşaması.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAYDET.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık:.
        /// </summary>
        internal static string title2 {
            get {
                return ResourceManager.GetString("title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Tipi.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        internal static string type2 {
            get {
                return ResourceManager.GetString("type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Geçmişi.
        /// </summary>
        internal static string yonetcilistbtn {
            get {
                return ResourceManager.GetString("yonetcilistbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici.
        /// </summary>
        internal static string yoneticibtn {
            get {
                return ResourceManager.GetString("yoneticibtn", resourceCulture);
            }
        }
    }
}
